// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClyRtt3vEJB2IWdnX8KtDkl5HoZApqsk8',
    appId: '1:725593178837:web:d9d87930730477d2d2585c',
    messagingSenderId: '725593178837',
    projectId: 'studybuddy-56c4a',
    authDomain: 'studybuddy-56c4a.firebaseapp.com',
    storageBucket: 'studybuddy-56c4a.firebasestorage.app',
    measurementId: 'G-47PGPXSD8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY7AYHC1IJu_GAshwKUoScsRopyOV4CvQ',
    appId: '1:725593178837:android:7a9a629f0999a2e8d2585c',
    messagingSenderId: '725593178837',
    projectId: 'studybuddy-56c4a',
    storageBucket: 'studybuddy-56c4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUkCw5ddhmpZh9TT764BP4GDwucGRlEkY',
    appId: '1:725593178837:ios:5906699e9f6f6d3fd2585c',
    messagingSenderId: '725593178837',
    projectId: 'studybuddy-56c4a',
    storageBucket: 'studybuddy-56c4a.firebasestorage.app',
    iosBundleId: 'com.example.studybuddy',
  );
}
